apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: merge-pr
spec:
  inputs:
    resources:
    - name: repo
      type: git
    - name: pr
      type: pullRequest
  steps:
  - name: merge
    image: gcr.io/cloud-builders/git
    command: ['bash']
    args:
    - -c
    - |
        set -ex
        if [ ! -f /workspace/pr/labels/lgtm ]; then
          "No lgtm label detected. Not merging."
          exit 0
        fi

        repo=$(python -c "import json; print json.load(open('/workspace/pr/head.json', 'r'))['Repo']")
        baserepo=$(python -c "import json; print json.load(open('/workspace/pr/base.json', 'r'))['Repo']")
        branch=$(python -c "import json; print json.load(open('/workspace/pr/head.json', 'r'))['Branch']")

        git config --global user.email "tekton@tekton.dev"
        git config --global user.name "Tekton Bot"
        cd /workspace/repo

        if [ "${baserepo}" == "${repo}" ]; then
          git fetch
          git checkout -b $branch origin/$branch
          git merge master --message="Merge branch '$branch'"
          git checkout master
          git merge --no-ff $branch
        else
          git checkout -b pr master
          git pull $repo $branch
          git checkout master
          git merge --no-ff pr
        fi
        git push origin master
