apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: review-pipeline-binding
spec:
  params:
  - name: gitrevision
    value: $(body.pull_request.head.sha)
  - name: gitrepositoryurl
    value: $(body.pull_request.head.repo.clone_url)
  - name: prurl
    value: $(body.pull_request.html_url)
  - name: repo
    value: $(body.pull_request.base.repo.full_name)
  - name: source
    value: github
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: comment-pipeline-binding
spec:
  params:
  - name: repo
    value: $(body.issue.html_url)
  - name: source
    value: github
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: deploy-pipeline-binding
spec:
  params:
  - name: branch
    value: $(body.ref)
  - name: repo
    value: $(body.repository.html_url)
---

apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: deploy-pipeline-binding-gitlab
spec:
  params:
  - name: branch
    value: $(body.ref)
  - name: repo
    value: $(body.repository.git_http_url)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: review-pipeline-binding-gitlab
spec:
  params:
  - name: gitrevision
    value: $(body.object_attributes.last_commit.id)
  - name: gitrepositoryurl
    value: $(body.object_attributes.source.git_http_url)
  - name: prurl
    value: $(body.object_attributes.url)
  - name: repo
    value: $(body.object_attributes.target.git_http_url)
  - name: source
    value: gitlab
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: comment-pipeline-binding-gitlab
spec:
  params:
  - name: repo
    value: $(body.merge_request.source.web_url)/merge_requests/$(body.merge_request.iid)
  - name: source
    value: gitlab
---

apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: review-pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: prurl
    description: The url to the PR
  - name: repo
    description: The repo to the PR
  - name: source
    description: github or gitlab
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: git-source-$(uid)
    spec:
      type: git
      params:
      - name: revision
        value: $(params.gitrevision)
      - name: url
        value: $(params.gitrepositoryurl)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: git-master-$(uid)
    spec:
      type: git
      params:
      - name: url
        value: $(params.gitrepositoryurl)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: pr-$(uid)
    spec:
      type: pullRequest
      params:
      - name: url
        value: $(params.prurl)
      secrets:
      - secretName: $(params.source)token
        secretKey: token
        fieldName: authToken
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: review-run-
    spec:
      pipelineRef:
        name: review
      resources:
      - name: repo
        resourceRef:
          name: git-source-$(uid)
      - name: pr
        resourceRef:
          name: pr-$(uid)
  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      generateName: merge-
    spec:
      taskRef:
        name: merge-pr
      inputs:
        resources:
        - name: repo
          resourceRef:
            name: git-master-$(uid)
        - name: pr
          resourceRef:
            name: pr-$(uid)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: comment-pipeline-template
spec:
  params:
  - name: repo
    description: The repo to the PR
  - name: source
    description: github or gitlab
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      generateName: lgtm-
    spec:
      taskRef:
        name: lgtm
      inputs:
        resources:
        - name: pr
          resourceSpec:
            type: pullRequest
            params:
            - name: url
              value: $(params.repo)
            secrets:
            - secretName: $(params.source)token
              secretKey: token
              fieldName: authToken
        params:
        - name: author
          value: "dlorenc" # from the githubtoken
      outputs:
        resources:
        - name: pr
          resourceSpec:
            type: pullRequest
            params:
            - name: url
              value: $(params.repo)
            secrets:
            - secretName: $(params.source)token
              secretKey: token
              fieldName: authToken
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: deploy-pipeline-template
spec:
  params:
  - name: branch
    description: The branch to the push
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      generateName: deploy-
    spec:
      taskRef:
        name: deploy
      inputs:
        resources:
        - name: repo
          resourceSpec:
            type: git
            params:
            - name: url
              value: $(params.repo)
        params:
        - name: branch
          value: $(params.branch)
      outputs:
        resources:
        - name: image
          resourceSpec:
            type: image
            params:
            - name: url
              value: gcr.io/dlorenc-vmtest2/foo
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-interceptor
spec:
  serviceType: LoadBalancer
  triggers:
  - name: pr-trig
    interceptor:
      github:
        eventType: pull_request
    bindings:
      - name: review-pipeline-binding
    template:
      name: review-pipeline-template
  - name: comment-trig
    interceptor:
      github:
        eventType: issue_comment
    bindings:
      - name: comment-pipeline-binding
    template:
      name: comment-pipeline-template
  - name: deploy-trig
    interceptor:
      github:
        eventType: push
    bindings:
      - name: deploy-pipeline-binding
    template:
      name: deploy-pipeline-template

  - name: pr-trig-gitlab
    interceptor:
      gitlab:
        eventType: Merge Request Hook
    bindings:
      - name: review-pipeline-binding-gitlab
    template:
      name: review-pipeline-template
  - name: comment-trig-gitlab
    interceptor:
      gitlab:
        eventType: Note Hook
    bindings:
      - name: comment-pipeline-binding-gitlab
    template:
      name: comment-pipeline-template
  - name: deploy-trig-gitlab
    interceptor:
      gitlab:
        eventType: Push Hook
    bindings:
      - name: deploy-pipeline-binding-gitlab
    template:
      name: deploy-pipeline-template
  
