apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: lgtm-
spec:
  taskRef:
    name: lgtm
  inputs:
    resources:
    - name: repo
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/dlorenc/skaffold-gitops
    - name: pr
      resourceSpec:
        type: pullRequest
        params:
        - name: url
          value: https://github.com/dlorenc/skaffold-gitops/pull/1
    params:
    - name: author
      value: "dlorenc" # from the githubtoken
  outputs:
    resources:
    - name: pr
      resourceSpec:
        type: pullRequest
        params:
        - name: url
          value: https://github.com/dlorenc/skaffold-gitops/pull/1
        secrets:
        - secretName: githubtoken
          secretKey: token
          fieldName: authToken
