apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: merge-pr-
spec:
  taskRef:
    name: merge-pr
  inputs:
    resources:
    - name: repo
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/dlorenc/skaffold-gitops
    params:
    - name: forkRepo
      value: https://github.com/dlorenc/skaffold-gitops
    - name: forkBranch
      value: pr
