apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: run-tests-
spec:
  taskRef:  
    name: run-tests
  inputs:
    resources:
    - name: repo
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/dlorenc/skaffold-gitops
    - name: pr
      resourceSpec:
        type: pullRequest
        params:
        - name: url
          value: https://github.com/dlorenc/skaffold-gitops/pull/1
  outputs:
    resources:
    - name: pr
      resourceSpec:
        type: pullRequest
        params:
        - name: url
          value: https://github.com/dlorenc/skaffold-gitops/pull/1
        secrets:
        - secretName: githubtoken
          secretKey: token
          fieldName: authToken
